package com.fields.business.object;

import java.math.BigDecimal;
import java.util.Date;

public class BalanceResume extends BalanceResumeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_resume.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_resume.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_resume.money_type
     *
     * @mbg.generated
     */
    private String moneyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_resume.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_resume.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_resume.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_resume.open_id
     *
     * @return the value of balance_resume.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_resume.open_id
     *
     * @param openId the value for balance_resume.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_resume.money
     *
     * @return the value of balance_resume.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_resume.money
     *
     * @param money the value for balance_resume.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_resume.money_type
     *
     * @return the value of balance_resume.money_type
     *
     * @mbg.generated
     */
    public String getMoneyType() {
        return moneyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_resume.money_type
     *
     * @param moneyType the value for balance_resume.money_type
     *
     * @mbg.generated
     */
    public void setMoneyType(String moneyType) {
        this.moneyType = moneyType == null ? null : moneyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_resume.order_type
     *
     * @return the value of balance_resume.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_resume.order_type
     *
     * @param orderType the value for balance_resume.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_resume.create_time
     *
     * @return the value of balance_resume.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_resume.create_time
     *
     * @param createTime the value for balance_resume.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_resume.update_time
     *
     * @return the value of balance_resume.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_resume.update_time
     *
     * @param updateTime the value for balance_resume.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}