package com.fields.business.object;

public class BalanceResumeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_resume.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_resume.data_src
     *
     * @mbg.generated
     */
    private String dataSrc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_resume.order_id
     *
     * @return the value of balance_resume.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_resume.order_id
     *
     * @param orderId the value for balance_resume.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_resume.data_src
     *
     * @return the value of balance_resume.data_src
     *
     * @mbg.generated
     */
    public String getDataSrc() {
        return dataSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_resume.data_src
     *
     * @param dataSrc the value for balance_resume.data_src
     *
     * @mbg.generated
     */
    public void setDataSrc(String dataSrc) {
        this.dataSrc = dataSrc == null ? null : dataSrc.trim();
    }
}