package com.fields.business.mapper;

import com.fields.business.object.BalanceInfo;
import com.fields.business.object.BalanceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BalanceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_info
     *
     * @mbg.generated
     */
    long countByExample(BalanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_info
     *
     * @mbg.generated
     */
    int deleteByExample(BalanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_info
     *
     * @mbg.generated
     */
    int insert(BalanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_info
     *
     * @mbg.generated
     */
    int insertSelective(BalanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_info
     *
     * @mbg.generated
     */
    List<BalanceInfo> selectByExample(BalanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_info
     *
     * @mbg.generated
     */
    BalanceInfo selectByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BalanceInfo record, @Param("example") BalanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BalanceInfo record, @Param("example") BalanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BalanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BalanceInfo record);
}